const messages = {
  "zh-CN": {
    appName: "AgentHub", skip: "跳到主要内容", nav: { overview: "总览", inventory: "能力库存", sync: "目标同步", git: "Git 历史", transactions: "事务历史", settings: "设置与诊断" },
    overview: { eyebrow: "CANONICAL SWITCHBOARD", title: "能力交换台", subtitle: "一处维护，清晰预览，安全同步到每个开发环境。", pending: "有待提交更改", clean: "工作区已提交", recent: "最近事务", emptyTx: "还没有同步事务。生成 Plan 后，每次应用与回滚都会出现在这里。", flowTitle: "从一个真源流向每个工具", channels: "通道已启用", resources: "项能力", capabilities: "能力流", ready: "已连接", notEnabled: "未启用", historyLayer: "内容历史", stateLayer: "业务状态", allCapabilities: "全部能力", totalResources: "Canonical 资源总数" },
    kinds: { skill: "Skills", mcp: "MCP", plugin: "Plugins", rule: "Rules" }, targets: { cursor: "Cursor", codex: "Codex", claude: "Claude Code" },
    common: { loading: "正在读取本机状态…", retry: "重试", close: "关闭", cancel: "取消", save: "保存更改", search: "搜索能力", clearSearch: "清除搜索", view: "查看", edit: "编辑" },
    inventory: { title: "能力库存", subtitle: "所有内容都以 Canonical 文件为准，业务状态单独保存在 SQLite。", empty: "这里还没有内容", emptyHint: "在 Canonical 中添加后，它会出现在这里。", digest: "内容摘要", importRule: "导入规则", newRule: "新建规则", editRule: "修改规则", importMarkdown: "选择 Markdown", ruleFormHint: "文件只用于初始化草稿，确认保存后才会写入 Canonical。", id: "稳定唯一标识（ID）", idPlaceholder: "例如：team-safety", idHint: "它是 Canonical 目录名，也是同步引用和历史追踪的固定身份。仅使用小写字母、数字、短横线或下划线；创建后不能修改。", displayName: "显示名称", activation: "激活方式", activationAlways: "始终启用", activationManual: "手动引用", activationPaths: "指定路径", paths: "适用路径", pathsHint: "每行一个相对路径或 glob。", targets: "兼容目标", body: "规则正文", bodyHint: "使用 Markdown 编写给 Agent 的明确规则。", saveRule: "保存规则", saving: "正在保存…", required: "请填写这个字段。", invalidId: "ID 必须是小写 slug，最长 80 个字符。", targetRequired: "至少选择一个兼容目标。", pathRequired: "按路径激活时至少填写一个路径。", fileTooLarge: "Markdown 文件不能超过 1 MB。", discardTitle: "放弃未保存的规则？", discardBody: "当前草稿中的修改不会写入 Canonical。", keepEditing: "继续编辑", discard: "放弃修改", loadFailed: "无法读取规则，请重试。", importedFile: "已从文件初始化草稿", viewDetails: "查看详情", detailLoadFailed: "无法读取能力详情，请重试。", files: "个文件", fileInventory: "文件清单", pluginPreviewHint: "插件仅预览 AgentHub Manifest 和文件清单；payload 不会被执行或直接渲染。", previewTruncated: "预览已截断" },
    sync: { title: "目标同步", subtitle: "先生成不会修改文件的 Plan，再确认完整覆盖范围。", plan: "生成预览 Plan", planning: "正在计算…", apply: "备份并执行覆盖", warning: "同步会删除宿主中多出的能力资源，但不会改动模型、主题、账户或权限等设置。", noPlan: "准备生成同步预览", noPlanHint: "AgentHub 会比较 Canonical 与目标宿主，逐项列出创建、替换与删除。", steps: "项文件变更", confirmTitle: "确认完整覆盖", confirmBody: "AgentHub 会先完整备份可写能力域，再写入并重新验证；任何验证失败都会自动回滚。", chooseTarget: "选择同步目标", review: "审阅变更", backup: "创建备份", verify: "写入并验证", ready: "Plan 已就绪", canonicalSnapshot: "Canonical 快照", capabilityChanges: "项能力变更", affected: "项受影响", create: "新增", update: "更新", delete: "删除", skip: "跳过", files: "个文件", fileDetails: "文件变更明细", noChanges: "目标已与 Canonical 一致" },
    git: { title: "Git 历史", subtitle: "Canonical 的每一次提交都由你决定，应用同步不要求工作区干净。", status: "工作区状态", diff: "当前差异", branch: "Canonical 仓库", clean: "工作区干净", noDiff: "当前没有未提交差异", commitTitle: "保存一个历史版本", commitHint: "只提交 AgentHub Canonical 文件，不会同步或修改任何宿主。", message: "提交说明", messagePlaceholder: "例如：添加团队安全规则", identity: "Git 身份", name: "姓名", email: "邮箱", identityHint: "仅写入 ~/.agenthub 仓库的本地 Git 配置。", commit: "提交 Canonical", committing: "正在提交…", history: "提交记录", noHistory: "还没有提交记录", nothingToCommit: "当前没有需要提交的 Canonical 更改。" },
    transactions: { subtitle: "每次 Apply 的备份、验证和回滚结果都保留在本机。", emptyTitle: "还没有事务记录", emptyBody: "当你第一次把 Canonical 同步到目标后，事务会按时间出现在这里。", rollback: "恢复到此次事务前", rollbackApply: "恢复到此次同步前", rollbackRollback: "恢复到此次回滚前", rollbackTitle: "恢复宿主历史状态？", rollbackBody: "AgentHub 将先备份目标当前状态，再恢复这次事务执行前的可写能力域并验证。Canonical 真源不会改变，恢复后会产生可检测的 drift。", rollbackAction: "备份当前状态并恢复", rollingBack: "正在恢复…", rollbackDone: "宿主状态已恢复并验证", historyLoadFailed: "无法读取完整事务历史。", verifiedApply: "写入结果已重新读取并验证", verifiedRollback: "历史状态已恢复并验证", backupAvailable: "本机备份可用", statusApplied: "已应用", statusRollbackApplied: "已恢复", statusRolledBack: "已自动回滚", statusRollbackFailed: "回滚失败", statusApplying: "正在应用", statusRollingBack: "正在回滚" },
    settings: { subtitle: "查看本地真源、业务数据库和同步通道状态。", canonical: "Canonical 真源", canonicalHint: "由 Git 记录可审阅的文件历史", database: "业务状态", databaseHint: "Plans、事务、目标与加密秘密索引", targets: "同步通道", targetsHint: "已启用的桌面工具目标", enabled: "个已启用", localOnly: "仅保存在本机", healthy: "状态正常" },
    init: { title: "建立 Canonical 真源", subtitle: "只扫描用户级全局位置。选择要导入的资源；未选择内容在首次同步时不会保留。", scan: "开始全局扫描", import: "导入所选并完成", importing: "正在验证并导入…", found: "发现的用户级资源", none: "未发现可导入资源，也可以创建空的 Canonical 真源。", selectAll: "全选", clear: "清空选择", selected: "已选择", recover: "清理未完成导入", recoverTitle: "清理未完成的初始化？", recoverBody: "只会删除 AgentHub Canonical 中上次失败产生的副本，不会修改 Cursor、Codex 或 Claude Code。", recoverAction: "清理并重新扫描" },
    toast: { planReady: "Plan 已生成", applied: "同步并验证成功", ruleSaved: "规则已保存到 Canonical", committed: "Canonical 历史已提交", failed: "操作失败" }
  },
  en: {
    appName: "AgentHub", skip: "Skip to main content", nav: { overview: "Overview", inventory: "Inventory", sync: "Target sync", git: "Git history", transactions: "Transactions", settings: "Settings & Doctor" },
    overview: { eyebrow: "CANONICAL SWITCHBOARD", title: "Capability switchboard", subtitle: "Maintain once, review clearly, and sync safely to every development environment.", pending: "Changes to commit", clean: "Working tree committed", recent: "Recent transactions", emptyTx: "No sync transactions yet. Plans, applies, and rollbacks will appear here.", flowTitle: "One source, every tool", channels: "channels enabled", resources: "capabilities", capabilities: "Capability flow", ready: "Connected", notEnabled: "Not enabled", historyLayer: "content history", stateLayer: "business state", allCapabilities: "All capabilities", totalResources: "Canonical resources" },
    kinds: { skill: "Skills", mcp: "MCP", plugin: "Plugins", rule: "Rules" }, targets: { cursor: "Cursor", codex: "Codex", claude: "Claude Code" },
    common: { loading: "Reading local state…", retry: "Retry", close: "Close", cancel: "Cancel", save: "Save changes", search: "Search capabilities", clearSearch: "Clear search", view: "View", edit: "Edit" },
    inventory: { title: "Capability inventory", subtitle: "Canonical files hold content while SQLite keeps business state separate.", empty: "Nothing here yet", emptyHint: "Add it to Canonical and it will appear here.", digest: "Content digest", importRule: "Import rule", newRule: "New rule", editRule: "Edit rule", importMarkdown: "Choose Markdown", ruleFormHint: "The file only initializes a draft. Canonical is written after you explicitly save.", id: "Stable unique ID", idPlaceholder: "For example: team-safety", idHint: "This is the Canonical directory name and the stable identity used by sync references and history. Use lowercase letters, numbers, hyphens, or underscores only; it cannot change after creation.", displayName: "Display name", activation: "Activation", activationAlways: "Always on", activationManual: "Manual reference", activationPaths: "Specific paths", paths: "Applicable paths", pathsHint: "One relative path or glob per line.", targets: "Compatible targets", body: "Rule body", bodyHint: "Write clear instructions for the agent in Markdown.", saveRule: "Save rule", saving: "Saving…", required: "This field is required.", invalidId: "ID must be a lowercase slug with no more than 80 characters.", targetRequired: "Choose at least one compatible target.", pathRequired: "Path activation requires at least one path.", fileTooLarge: "Markdown files must be no larger than 1 MB.", discardTitle: "Discard unsaved rule?", discardBody: "Changes in this draft will not be written to Canonical.", keepEditing: "Keep editing", discard: "Discard changes", loadFailed: "The rule could not be loaded. Try again.", importedFile: "Draft initialized from file", viewDetails: "View details", detailLoadFailed: "Capability details could not be loaded. Try again.", files: "files", fileInventory: "File inventory", pluginPreviewHint: "Plugins preview only the AgentHub manifest and file inventory. Payloads are neither executed nor rendered.", previewTruncated: "Preview truncated" },
    sync: { title: "Target sync", subtitle: "Create a zero-write Plan, then review the full replacement before applying.", plan: "Create preview Plan", planning: "Calculating…", apply: "Back up and apply", warning: "Sync removes extra host capabilities while preserving models, themes, accounts, permissions, and other settings.", noPlan: "Ready to preview sync", noPlanHint: "AgentHub compares Canonical with the target and lists every create, replace, and delete.", steps: "file changes", confirmTitle: "Confirm full replacement", confirmBody: "AgentHub fully backs up writable capability domains, writes, then validates. Any verification failure rolls back automatically.", chooseTarget: "Choose a target", review: "Review changes", backup: "Create backup", verify: "Write and verify", ready: "Plan ready", canonicalSnapshot: "Canonical snapshot", capabilityChanges: "capability changes", affected: "Affected", create: "Create", update: "Update", delete: "Delete", skip: "Skip", files: "files", fileDetails: "File change details", noChanges: "Target matches Canonical" },
    git: { title: "Git history", subtitle: "You decide every Canonical commit; applying sync does not require a clean working tree.", status: "Working tree", diff: "Current diff", branch: "Canonical repository", clean: "Working tree is clean", noDiff: "No uncommitted differences", commitTitle: "Save a history version", commitHint: "Only AgentHub Canonical files are committed. No host is synced or modified.", message: "Commit message", messagePlaceholder: "For example: add team safety rules", identity: "Git identity", name: "Name", email: "Email", identityHint: "Stored only in the local Git config for ~/.agenthub.", commit: "Commit Canonical", committing: "Committing…", history: "Commit history", noHistory: "No commits yet", nothingToCommit: "There are no Canonical changes to commit." },
    transactions: { subtitle: "Backups, verification, and rollback results remain available for every Apply.", emptyTitle: "No transactions yet", emptyBody: "Your first Canonical sync will create a timestamped transaction here.", rollback: "Restore state before transaction", rollbackApply: "Restore state before this sync", rollbackRollback: "Restore state before this rollback", rollbackTitle: "Restore historical host state?", rollbackBody: "AgentHub first backs up the target's current state, then restores and verifies the writable capability domains captured before this transaction. Canonical is unchanged, so the restored host may intentionally drift.", rollbackAction: "Back up current state and restore", rollingBack: "Restoring…", rollbackDone: "Host state restored and verified", historyLoadFailed: "The full transaction history could not be loaded.", verifiedApply: "Written state re-read and verified", verifiedRollback: "Historical state restored and verified", backupAvailable: "Local backup available", statusApplied: "Applied", statusRollbackApplied: "Restored", statusRolledBack: "Auto-rolled back", statusRollbackFailed: "Rollback failed", statusApplying: "Applying", statusRollingBack: "Rolling back" },
    settings: { subtitle: "Inspect the local source, business database, and sync channel status.", canonical: "Canonical source", canonicalHint: "Reviewable file history tracked by Git", database: "Business state", databaseHint: "Plans, transactions, targets, and encrypted secret indexes", targets: "Sync channels", targetsHint: "Enabled desktop tool targets", enabled: "enabled", localOnly: "Stored only on this device", healthy: "Healthy" },
    init: { title: "Create the Canonical source", subtitle: "Only user-global locations are scanned. Select resources to import; unselected content is not retained on first sync.", scan: "Scan global resources", import: "Import selected and finish", importing: "Validating and importing…", found: "Discovered user resources", none: "No importable resources found. You can create an empty Canonical source.", selectAll: "Select all", clear: "Clear selection", selected: "selected", recover: "Clean incomplete import", recoverTitle: "Clean the incomplete initialization?", recoverBody: "This only removes copies left in AgentHub Canonical by the failed import. Cursor, Codex and Claude Code are not changed.", recoverAction: "Clean and scan again" },
    toast: { planReady: "Plan created", applied: "Sync verified", ruleSaved: "Rule saved to Canonical", committed: "Canonical history committed", failed: "Operation failed" }
  }
} as const;
type Locale = keyof typeof messages;
let locale: Locale = "zh-CN";
export function setLocale(next: Locale) { locale = next; }
export function t(path: string): string { let value: unknown = messages[locale]; for (const part of path.split(".")) value = (value as Record<string, unknown>)[part]; return String(value ?? path); }
