const messages = {
  "zh-CN": {
    hosts: { title: "宿主资源", subtitle: "查看各工具当前的用户级能力，区分 Canonical 对应项与宿主自有内容，并安全清理可写资源。", rescan: "重新扫描", chooseTarget: "选择宿主", scanning: "正在读取宿主资源…", resources: "项资源", canonicalMatch: "对应 Canonical", hostOnly: "宿主自有", constraint: "受保护约束", legendHint: "来源标签只描述当前对应关系，不代表文件所有权。", canonicalId: "Canonical ID", notCanonical: "AgentHub 中没有对应内容", empty: "未发现资源", emptyHint: "该宿主的这个用户级能力域当前为空。", selected: "项已选择", cleanupHint: "删除前会备份；Canonical 内容不会改变。", deleteSelected: "删除所选宿主资源", deleteTitle: "删除这些宿主资源？", deleteBody: "AgentHub 会重新扫描并备份所有受影响路径，然后只删除列出的资源。失败时会自动尝试恢复。", deleteAction: "备份并删除", driftWarning: "其中包含 Canonical 对应项。删除会产生 drift；已开启的自动同步可能在下次 AgentHub 修改时重新创建它。", deleted: "项宿主资源已删除并备份", relations: { canonical_match: "对应 Canonical", host_only: "宿主自有", constraint: "受保护" }, constraints: { claude_plugins_cli_managed: "Claude Code 插件由官方 CLI 管理，禁止直接删除目录。", codex_plugins_cli_managed: "Codex 插件市场与缓存由官方 CLI 管理，禁止直接删除目录。" } },
    appName: "AgentHub", skip: "跳到主要内容", nav: { overview: "总览", inventory: "能力库存", hosts: "宿主资源", sync: "目标同步", git: "Git 历史", transactions: "事务历史", settings: "设置与诊断" },
    overview: { eyebrow: "CANONICAL SWITCHBOARD", title: "能力交换台", subtitle: "一处维护，清晰预览，安全同步到每个开发环境。", pending: "有待提交更改", clean: "工作区已提交", recent: "最近事务", emptyTx: "还没有同步事务。生成 Plan 后，每次应用与回滚都会出现在这里。", flowTitle: "从一个真源流向每个工具", channels: "通道已同步", autoChannels: "个自动目标", resources: "项能力", capabilities: "能力流", ready: "已同步", autoReady: "自动同步", notEnabled: "未启用", historyLayer: "内容历史", stateLayer: "业务状态", allCapabilities: "全部能力", totalResources: "Canonical 资源总数" },
    kinds: { skill: "Skills", mcp: "MCP", plugin: "Plugins", rule: "Rules" }, targets: { agents: "共享 Agents", cursor: "Cursor", codex: "Codex", claude: "Claude Code" },
    common: { loading: "正在读取本机状态…", retry: "重试", close: "关闭", cancel: "取消", save: "保存更改", search: "搜索能力", clearSearch: "清除搜索", view: "查看", edit: "编辑", logHint: "诊断日志位置：" },
    inventory: { title: "能力库存", subtitle: "所有内容都以 Canonical 文件为准，业务状态单独保存在 SQLite。", empty: "这里还没有内容", emptyHint: "在 Canonical 中添加后，它会出现在这里。", digest: "内容摘要", importRule: "导入规则", newRule: "新建规则", editRule: "修改规则", delete: "删除能力", deleteTitle: "从 AgentHub 删除这项能力？", deleteBody: "该能力会从 Canonical 真源删除；已启用自动同步且包含它的目标会通过备份事务删除对应投影。其他未选择的宿主能力不会被直接修改。", deleteAction: "删除并同步已启用目标", importMarkdown: "选择 Markdown", ruleFormHint: "文件只用于初始化草稿，确认保存后才会写入 Canonical。", id: "稳定唯一标识（ID）", idPlaceholder: "例如：team-safety", idHint: "它是 Canonical 目录名，也是同步引用和历史追踪的固定身份。仅使用小写字母、数字、短横线或下划线；创建后不能修改。", displayName: "显示名称", activation: "激活方式", activationAlways: "始终启用", activationManual: "手动引用", activationPaths: "指定路径", paths: "适用路径", pathsHint: "每行一个相对路径或 glob。", targets: "兼容目标", body: "规则正文", bodyHint: "使用 Markdown 编写给 Agent 的明确规则。", saveRule: "保存规则", saving: "正在保存…", required: "请填写这个字段。", invalidId: "ID 必须是小写 slug，最长 80 个字符。", targetRequired: "至少选择一个兼容目标。", pathRequired: "按路径激活时至少填写一个路径。", fileTooLarge: "Markdown 文件不能超过 1 MB。", discardTitle: "放弃未保存的规则？", discardBody: "当前草稿中的修改不会写入 Canonical。", keepEditing: "继续编辑", discard: "放弃修改", loadFailed: "无法读取规则，请重试。", importedFile: "已从文件初始化草稿", viewDetails: "查看详情", detailLoadFailed: "无法读取能力详情，请重试。", files: "个文件", fileInventory: "文件清单", pluginPreviewHint: "插件仅预览 AgentHub Manifest 和文件清单；payload 不会被执行或直接渲染。", previewTruncated: "预览已截断" },
    sync: { title: "目标同步", subtitle: "先选择目标和范围；开启自动同步后，AgentHub 的后续修改会立即投影到该目标。", plan: "预览 Plan", planning: "正在计算…", apply: "备份并执行覆盖", warning: "同步会删除所选能力域中宿主多出的资源，但不会改动模型、主题、账户或权限等设置。", noPlan: "预览一次，或开启自动同步", noPlanHint: "Plan 用于审阅当前差异；自动同步会保存这次范围，并在每次 AgentHub 写入后自动备份、同步和验证。", steps: "项文件变更", confirmTitle: "确认完整覆盖", confirmBody: "AgentHub 会先完整备份可写能力域，再写入并重新验证；任何验证失败都会自动回滚。", autoConfirmTitle: "开启自动同步？", autoConfirmBody: "请再次核对下方能力清单。AgentHub 会先同步当前范围，成功后保存；以后仅自动同步这些能力。不会扫描或合并宿主侧手工修改。", autoConfirmAction: "同步当前范围并开启", disableAutoTitle: "关闭自动同步？", disableAutoBody: "以后修改 AgentHub 时将不再自动更新此目标。宿主当前内容和已有回滚事务不会改变。", disableAutoAction: "关闭自动同步", chooseTarget: "选择同步目标", review: "审阅变更", backup: "创建备份", verify: "写入并验证", ready: "Plan 已就绪", canonicalSnapshot: "Canonical 快照", capabilityChanges: "项能力变更", affected: "项受影响", create: "新增", update: "替换", delete: "删除", skip: "跳过", files: "个文件", exactChanges: "具体能力变更", domainProjection: "组合能力域", noneSelected: "未选择", fileDetails: "文件变更明细", noChanges: "目标已与 Canonical 一致", scopeTitle: "选择同步范围", scopeHint: "逐项选择要同步的能力；该清单同时用于 Plan 和自动同步，已启用目标修改后需要保存。", scopeDeleteHint: "取消选择后生成 Plan，可先看到目标中的对应删除项；只有确认执行或保存自动同步范围后才会修改宿主。", selected: "项已选择", selectAll: "全部选择", clearAll: "清空选择", rulesToggle: "同步 Canonical Rules 到目标", included: "已包含", excluded: "不触碰", enableAuto: "开启自动同步", updateAuto: "保存自动同步范围", disableAuto: "关闭自动同步", autoEnabled: "自动同步已开启", autoOn: "自动同步中" },
    git: { title: "Git 历史", subtitle: "Canonical 的每一次提交都由你决定，应用同步不要求工作区干净。", status: "工作区状态", diff: "当前差异", branch: "Canonical 仓库", clean: "工作区干净", noDiff: "当前没有未提交差异", commitTitle: "保存一个历史版本", commitHint: "只提交 AgentHub Canonical 文件，不会同步或修改任何宿主。", message: "提交说明", messagePlaceholder: "例如：添加团队安全规则", identity: "Git 身份", name: "姓名", email: "邮箱", identityHint: "仅写入 ~/.agenthub 仓库的本地 Git 配置。", commit: "提交 Canonical", committing: "正在提交…", history: "提交记录", noHistory: "还没有提交记录", nothingToCommit: "当前没有需要提交的 Canonical 更改。" },
    transactions: { subtitle: "每次实际写入的备份、验证和回滚结果都保留在本机；连续自动同步会折叠显示。", emptyTitle: "还没有事务记录", emptyBody: "当你第一次把 Canonical 同步到目标后，事务会按时间出现在这里。", rollback: "恢复到此次事务前", rollbackApply: "恢复到此次同步前", rollbackRollback: "恢复到此次回滚前", rollbackTitle: "恢复宿主历史状态？", rollbackBody: "AgentHub 将先备份目标当前状态，再恢复这次事务执行前的可写能力域并验证。Canonical 真源不会改变，恢复后会产生可检测的 drift。", rollbackAction: "备份当前状态并恢复", rollingBack: "正在恢复…", rollbackDone: "宿主状态已恢复并验证", historyLoadFailed: "无法读取完整事务历史。", verifiedApply: "写入结果已重新读取并验证", verifiedRollback: "历史状态已恢复并验证", backupAvailable: "本机备份可用", modeReviewed: "Plan 审阅", modeAuto: "自动同步", modeRollback: "手动回滚", autoBatch: "自动同步", runs: "次", statusApplied: "已应用", statusRollbackApplied: "已恢复", statusRolledBack: "已自动回滚", statusRollbackFailed: "回滚失败", statusApplying: "正在应用", statusRollingBack: "正在回滚" },
    settings: { subtitle: "查看本地真源、业务数据库和同步通道状态。", canonical: "Canonical 真源", canonicalHint: "由 Git 记录可审阅的文件历史", database: "业务状态", databaseHint: "Plans、事务、目标与加密秘密索引", targets: "同步通道", targetsHint: "已启用的桌面工具目标", logs: "诊断日志", logsHint: "发生错误时可复制此目录中的最新日志", loadingPath: "正在读取日志位置…", gitReady: "Git 可用", gitMissing: "未检测到 Git", enabled: "个已启用", localOnly: "仅保存在本机", healthy: "状态正常" },
    init: { title: "建立 Canonical 真源", subtitle: "只扫描用户级全局位置。选择要导入的资源；未选择内容在首次同步时不会保留。", scan: "开始全局扫描", import: "导入所选并完成", importing: "正在验证并导入…", found: "发现的用户级资源", groups: "能力分类", discovered: "项发现", selectGroup: "选择本类", clearGroup: "清空本类", emptyGroup: "未发现此类能力", emptyGroupHint: "当前用户级全局位置中没有可显示的此类资源。", duplicate: "与另一来源内容相同；同时选择也只会导入一份", none: "未发现可导入资源，也可以创建空的 Canonical 真源。", selectAll: "全选", clear: "清空选择", selected: "已选择", importable: "可导入", rejected: "需处理", notImportable: "不可导入", rule_empty: "规则文件为空，请先补充内容", rule_too_large: "规则文件超过 1 MB", rule_invalid_encoding: "规则文件不是 UTF-8 编码", recover: "清理未完成导入", recoverTitle: "清理未完成的初始化？", recoverBody: "只会删除 AgentHub Canonical 中上次失败产生的副本，不会修改 Cursor、Codex 或 Claude Code。", recoverAction: "清理并重新扫描", legacyReset: "重置失败的初始化", legacyResetConfirm: "将删除上次失败导入到 AgentHub 的 Canonical 副本并重新开始。不会修改任何宿主。确定继续吗？" },
    toast: { planReady: "Plan 已生成", applied: "已按 Plan 同步并验证", autoEnabledSynced: "当前状态已同步，后续修改将自动同步", autoEnabled: "目标已是最新状态，自动同步已开启", autoDisabled: "自动同步已关闭", ruleSaved: "规则已保存到 Canonical", ruleSavedAutoSynced: "规则已保存并自动同步到", ruleSavedAutoFailed: "规则已保存，但自动同步失败：", capabilityDeleted: "能力已从 Canonical 删除", capabilityDeletedAutoFailed: "能力已删除，但自动同步失败：", committed: "Canonical 历史已提交", failed: "操作失败" }
  },
  en: {
    appName: "AgentHub", skip: "Skip to main content", nav: { overview: "Overview", inventory: "Inventory", sync: "Target sync", git: "Git history", transactions: "Transactions", settings: "Settings & Doctor" },
    overview: { eyebrow: "CANONICAL SWITCHBOARD", title: "Capability switchboard", subtitle: "Maintain once, review clearly, and sync safely to every development environment.", pending: "Changes to commit", clean: "Working tree committed", recent: "Recent transactions", emptyTx: "No sync transactions yet. Plans, applies, and rollbacks will appear here.", flowTitle: "One source, every tool", channels: "channels synced", autoChannels: "automatic targets", resources: "capabilities", capabilities: "Capability flow", ready: "Synced", autoReady: "Automatic sync", notEnabled: "Not enabled", historyLayer: "content history", stateLayer: "business state", allCapabilities: "All capabilities", totalResources: "Canonical resources" },
    kinds: { skill: "Skills", mcp: "MCP", plugin: "Plugins", rule: "Rules" }, targets: { agents: "Shared Agents", cursor: "Cursor", codex: "Codex", claude: "Claude Code" },
    common: { loading: "Reading local state…", retry: "Retry", close: "Close", cancel: "Cancel", save: "Save changes", search: "Search capabilities", clearSearch: "Clear search", view: "View", edit: "Edit", logHint: "Diagnostic logs: " },
    inventory: { title: "Capability inventory", subtitle: "Canonical files hold content while SQLite keeps business state separate.", empty: "Nothing here yet", emptyHint: "Add it to Canonical and it will appear here.", digest: "Content digest", importRule: "Import rule", newRule: "New rule", editRule: "Edit rule", delete: "Delete capability", deleteTitle: "Delete this capability from AgentHub?", deleteBody: "The capability is removed from Canonical. Enabled automatic-sync targets whose scope includes it remove the projection through a backed-up transaction. Other unselected host capabilities are not edited directly.", deleteAction: "Delete and sync enabled targets", importMarkdown: "Choose Markdown", ruleFormHint: "The file only initializes a draft. Canonical is written after you explicitly save.", id: "Stable unique ID", idPlaceholder: "For example: team-safety", idHint: "This is the Canonical directory name and the stable identity used by sync references and history. Use lowercase letters, numbers, hyphens, or underscores only; it cannot change after creation.", displayName: "Display name", activation: "Activation", activationAlways: "Always on", activationManual: "Manual reference", activationPaths: "Specific paths", paths: "Applicable paths", pathsHint: "One relative path or glob per line.", targets: "Compatible targets", body: "Rule body", bodyHint: "Write clear instructions for the agent in Markdown.", saveRule: "Save rule", saving: "Saving…", required: "This field is required.", invalidId: "ID must be a lowercase slug with no more than 80 characters.", targetRequired: "Choose at least one compatible target.", pathRequired: "Path activation requires at least one path.", fileTooLarge: "Markdown files must be no larger than 1 MB.", discardTitle: "Discard unsaved rule?", discardBody: "Changes in this draft will not be written to Canonical.", keepEditing: "Keep editing", discard: "Discard changes", loadFailed: "The rule could not be loaded. Try again.", importedFile: "Draft initialized from file", viewDetails: "View details", detailLoadFailed: "Capability details could not be loaded. Try again.", files: "files", fileInventory: "File inventory", pluginPreviewHint: "Plugins preview only the AgentHub manifest and file inventory. Payloads are neither executed nor rendered.", previewTruncated: "Preview truncated" },
    sync: { title: "Target sync", subtitle: "Choose a target and scope. Once enabled, later AgentHub changes are projected automatically.", plan: "Preview Plan", planning: "Calculating…", apply: "Back up and apply", warning: "Sync removes extra host resources inside the selected domains while preserving models, themes, accounts, permissions, and other settings.", noPlan: "Preview once, or enable automatic sync", noPlanHint: "Plan reviews the current difference. Automatic sync saves this scope and backs up, syncs, and verifies after every AgentHub write.", steps: "file changes", confirmTitle: "Confirm full replacement", confirmBody: "AgentHub fully backs up writable capability domains, writes, then validates. Any verification failure rolls back automatically.", autoConfirmTitle: "Enable automatic sync?", autoConfirmBody: "Review the named scope below. AgentHub syncs it once, then saves it so only those capabilities are automatically synchronized. Host-side edits are not scanned or merged.", autoConfirmAction: "Sync this scope and enable", disableAutoTitle: "Disable automatic sync?", disableAutoBody: "Future AgentHub changes will no longer update this target automatically. Current host content and existing rollback transactions remain unchanged.", disableAutoAction: "Disable automatic sync", chooseTarget: "Choose a target", review: "Review changes", backup: "Create backup", verify: "Write and verify", ready: "Plan ready", canonicalSnapshot: "Canonical snapshot", capabilityChanges: "capability changes", affected: "Affected", create: "Create", update: "Replace", delete: "Delete", skip: "Skip", files: "files", exactChanges: "Exact capability changes", domainProjection: "Combined capability domain", noneSelected: "None selected", fileDetails: "File change details", noChanges: "Target matches Canonical", scopeTitle: "Choose sync scope", scopeHint: "Select individual capabilities for both Plans and automatic sync. Save the scope after changing an enabled target.", scopeDeleteHint: "Deselect a capability and preview the Plan to see its target deletion. The host changes only after Apply or saving the automatic scope.", selected: "selected", selectAll: "Select all", clearAll: "Clear all", rulesToggle: "Sync Canonical Rules to the target", included: "Included", excluded: "Do not touch", enableAuto: "Enable automatic sync", updateAuto: "Save automatic sync scope", disableAuto: "Disable automatic sync", autoEnabled: "Automatic sync enabled", autoOn: "Automatic sync on" },
    git: { title: "Git history", subtitle: "You decide every Canonical commit; applying sync does not require a clean working tree.", status: "Working tree", diff: "Current diff", branch: "Canonical repository", clean: "Working tree is clean", noDiff: "No uncommitted differences", commitTitle: "Save a history version", commitHint: "Only AgentHub Canonical files are committed. No host is synced or modified.", message: "Commit message", messagePlaceholder: "For example: add team safety rules", identity: "Git identity", name: "Name", email: "Email", identityHint: "Stored only in the local Git config for ~/.agenthub.", commit: "Commit Canonical", committing: "Committing…", history: "Commit history", noHistory: "No commits yet", nothingToCommit: "There are no Canonical changes to commit." },
    transactions: { subtitle: "Every real write keeps its local backup, verification, and rollback result; consecutive automatic sync runs are collapsed.", emptyTitle: "No transactions yet", emptyBody: "Your first Canonical sync will create a timestamped transaction here.", rollback: "Restore state before transaction", rollbackApply: "Restore state before this sync", rollbackRollback: "Restore state before this rollback", rollbackTitle: "Restore historical host state?", rollbackBody: "AgentHub first backs up the target's current state, then restores and verifies the writable capability domains captured before this transaction. Canonical is unchanged, so the restored host may intentionally drift.", rollbackAction: "Back up current state and restore", rollingBack: "Restoring…", rollbackDone: "Host state restored and verified", historyLoadFailed: "The full transaction history could not be loaded.", verifiedApply: "Written state re-read and verified", verifiedRollback: "Historical state restored and verified", backupAvailable: "Local backup available", modeReviewed: "Plan reviewed", modeAuto: "Automatic sync", modeRollback: "Manual rollback", autoBatch: "Automatic sync", runs: "runs", statusApplied: "Applied", statusRollbackApplied: "Restored", statusRolledBack: "Auto-rolled back", statusRollbackFailed: "Rollback failed", statusApplying: "Applying", statusRollingBack: "Rolling back" },
    settings: { subtitle: "Inspect the local source, business database, and sync channel status.", canonical: "Canonical source", canonicalHint: "Reviewable file history tracked by Git", database: "Business state", databaseHint: "Plans, transactions, targets, and encrypted secret indexes", targets: "Sync channels", targetsHint: "Enabled desktop tool targets", logs: "Diagnostic logs", logsHint: "Copy the newest file from this folder when reporting an error", loadingPath: "Reading log location…", gitReady: "Git available", gitMissing: "Git not found", enabled: "enabled", localOnly: "Stored only on this device", healthy: "Healthy" },
    init: { title: "Create the Canonical source", subtitle: "Only user-global locations are scanned. Select resources to import; unselected content is not retained on first sync.", scan: "Scan global resources", import: "Import selected and finish", importing: "Validating and importing…", found: "Discovered user resources", groups: "Capability groups", discovered: "discovered", selectGroup: "Select group", clearGroup: "Clear group", emptyGroup: "No capabilities in this group", emptyGroupHint: "No matching user-global resources were found for this capability type.", duplicate: "Same content as another source; selecting both still imports one copy", none: "No importable resources found. You can create an empty Canonical source.", selectAll: "Select all", clear: "Clear selection", selected: "selected", importable: "importable", rejected: "need attention", notImportable: "Unavailable", rule_empty: "The rule file is empty; add content first", rule_too_large: "The rule file exceeds 1 MB", rule_invalid_encoding: "The rule file is not UTF-8", recover: "Clean incomplete import", recoverTitle: "Clean the incomplete initialization?", recoverBody: "This only removes copies left in AgentHub Canonical by the failed import. Cursor, Codex and Claude Code are not changed.", recoverAction: "Clean and scan again", legacyReset: "Reset failed initialization", legacyResetConfirm: "This removes Canonical copies from the failed AgentHub import and starts again. No host is modified. Continue?" },
    toast: { planReady: "Plan created", applied: "Plan applied and verified", autoEnabledSynced: "Current state synced; future changes will sync automatically", autoEnabled: "Target is current and automatic sync is enabled", autoDisabled: "Automatic sync disabled", ruleSaved: "Rule saved to Canonical", ruleSavedAutoSynced: "Rule saved and automatically synced to", ruleSavedAutoFailed: "Rule saved, but automatic sync failed for:", capabilityDeleted: "Capability deleted from Canonical", capabilityDeletedAutoFailed: "Capability deleted, but automatic sync failed for:", committed: "Canonical history committed", failed: "Operation failed" }
  }
} as const;
const extraMessages: Record<string, Record<string, unknown>> = {
  "zh-CN": {
    inventory: { scanImport: "扫描并导入", scanImportTitle: "从宿主反向导入", scanImportBody: "重新扫描用户级全局位置。只把你选择的新内容复制进 Canonical；相同内容会自动去重，宿主不会被修改。", importScanned: "导入所选", importingScan: "正在安全导入…", alreadyCanonical: "Canonical 已有相同内容", scanImported: "项已导入", scanSkipped: "项重复已跳过", scanAutoFailed: "个自动同步目标失败" },
    sync: { agentsHint: "共享 Skills 目录会被支持 Agent Skills 的多个工具读取；选中管理且清空列表即可显式清空该目录。", strictActive: "强制覆盖已开启", clearManaged: "清空受管域", notManaged: "不管理", cliManaged: "CLI 管理", manageDomain: "管理这个能力域", emptyMeansClear: "选中管理但不选资源时，将清空目标对应能力域", domainUntouched: "不读取、不写入该能力域", rulesIncludedHint: "用全部 Canonical Rules 重建目标规则域", claudePluginConstraint: "Claude Code 的插件库由官方 plugin CLI 管理。v0.1 会保留 ~/.claude/plugins 并跳过该域，避免破坏登录、市场和已安装插件状态。", codexPluginConstraint: "Codex 插件由个人 marketplace、安装缓存与配置共同管理。v0.1 会保留这些状态并跳过插件域，避免用目录覆盖破坏市场与安装记录。" },
    settings: { coverageTitle: "覆盖策略", coverageHint: "选择 AgentHub 是严格真源，还是只管理你明确选择的能力域。", strict: "强制覆盖", scoped: "选择性管理", strictOverwrite: "AgentHub 强制覆盖所有可写能力域", strictOverwriteHint: "下次 Plan 或自动同步会使用全部 Canonical 能力；宿主额外内容会删除。", syncAfterImport: "反向导入后运行自动同步", syncAfterImportHint: "导入先写入 Canonical，再按已启用目标的保存范围同步；关闭时只导入，不修改任何宿主。", planGuard: "手动同步仍需 Plan 确认", backupGuard: "每次写入仍先备份并验证", vendorGuard: "厂商、组织与只读能力始终保留" },
  },
  en: {
    nav: { hosts: "Host resources" },
    hosts: { title: "Host resources", subtitle: "Inspect user-level capabilities in each tool, distinguish Canonical matches from host content, and safely clean writable resources.", rescan: "Rescan", chooseTarget: "Choose a host", scanning: "Reading host resources…", resources: "resources", canonicalMatch: "Canonical match", hostOnly: "Host only", constraint: "Protected constraint", legendHint: "Relationship labels describe the current match; they do not claim file ownership.", canonicalId: "Canonical ID", notCanonical: "No corresponding AgentHub content", empty: "No resources found", emptyHint: "This user-level host capability domain is empty.", selected: "selected", cleanupHint: "Affected paths are backed up first; Canonical is unchanged.", deleteSelected: "Delete selected host resources", deleteTitle: "Delete these host resources?", deleteBody: "AgentHub rescans and backs up every affected path, then deletes only the listed resources. Failure triggers an automatic restore attempt.", deleteAction: "Back up and delete", driftWarning: "This includes Canonical matches. Deletion creates drift, and automatic sync may recreate them after the next AgentHub mutation.", deleted: "host resources deleted and backed up", relations: { canonical_match: "Canonical match", host_only: "Host only", constraint: "Protected" }, constraints: { claude_plugins_cli_managed: "Claude Code plugins are managed by the official CLI; raw directory deletion is disabled.", codex_plugins_cli_managed: "Codex marketplace and cache state are CLI-managed; raw directory deletion is disabled." } },
    inventory: { scanImport: "Scan & import", scanImportTitle: "Import back from hosts", scanImportBody: "Rescan user-global locations. Only selected new content is copied into Canonical; identical content is deduplicated and hosts are never modified.", importScanned: "Import selected", importingScan: "Importing safely…", alreadyCanonical: "Identical content is already Canonical", scanImported: "imported", scanSkipped: "duplicates skipped", scanAutoFailed: "automatic targets failed" },
    sync: { agentsHint: "This shared Skills directory is loaded by multiple Agent Skills clients. Manage it with an empty selection to explicitly clear it.", strictActive: "Strict overwrite on", clearManaged: "Clear managed domains", notManaged: "Unmanaged", cliManaged: "CLI managed", manageDomain: "Manage this domain", emptyMeansClear: "A managed domain with no selected resources is cleared on the target", domainUntouched: "This domain is neither read nor written", rulesIncludedHint: "Rebuild the target Rules domain from every Canonical Rule", claudePluginConstraint: "Claude Code's plugin store is managed by the official plugin CLI. v0.1 preserves ~/.claude/plugins and skips this domain to protect login, marketplace, and installed-plugin state.", codexPluginConstraint: "Codex plugins span a personal marketplace, install cache, and configuration. v0.1 preserves that state and skips the plugin domain instead of corrupting marketplace records with a directory overwrite." },
    settings: { coverageTitle: "Coverage policy", coverageHint: "Choose whether AgentHub is a strict source of truth or manages only explicitly selected domains.", strict: "Strict overwrite", scoped: "Scoped management", strictOverwrite: "Force AgentHub over all writable capability domains", strictOverwriteHint: "The next Plan or automatic sync uses every Canonical capability and deletes extra host content.", syncAfterImport: "Run automatic sync after reverse import", syncAfterImportHint: "Import writes Canonical first, then syncs saved scopes for enabled targets. When off, import never modifies a host.", planGuard: "Manual sync still requires Plan confirmation", backupGuard: "Every write is still backed up and verified", vendorGuard: "Vendor, organization, and read-only capabilities remain protected" },
  },
};
type Locale = keyof typeof messages;
let locale: Locale = "zh-CN";
export function setLocale(next: Locale) { locale = next; }
export function t(path: string): string {
  let value: unknown = extraMessages[locale];
  for (const part of path.split(".")) value = (value as Record<string, unknown> | undefined)?.[part];
  if (value !== undefined) return String(value);
  value = messages[locale];
  for (const part of path.split(".")) value = (value as Record<string, unknown>)[part];
  return String(value ?? path);
}
